// -----------------------------------------------------------
// Auto-generated by onshape_uploader.py for: Moth Hull
// Paste into a Feature Studio, then add a Loft across the
// named sketch planes.
// -----------------------------------------------------------

FeatureScript 2176;
import(path : "onshape/std/geometry.fs", version : "2176.0");

annotation { "Feature Type Name" : "Hull Planes" }
export const hullPlanes = defineFeature(function(context is Context,
                                                  id is Id,
                                                  definition is map)
precondition
{
}
{

    // Station 0: X = 0 mm  (station_00_x0000mm.dxf)
    opPlane(context, id + "plane_00", {
        "plane" : plane(vector(0, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 1: X = 335 mm  (station_01_x0335mm.dxf)
    opPlane(context, id + "plane_01", {
        "plane" : plane(vector(335, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 2: X = 1100 mm  (station_02_x1100mm.dxf)
    opPlane(context, id + "plane_02", {
        "plane" : plane(vector(1100, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 3: X = 1700 mm  (station_03_x1700mm.dxf)
    opPlane(context, id + "plane_03", {
        "plane" : plane(vector(1700, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 4: X = 2300 mm  (station_04_x2300mm.dxf)
    opPlane(context, id + "plane_04", {
        "plane" : plane(vector(2300, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 5: X = 2850 mm  (station_05_x2850mm.dxf)
    opPlane(context, id + "plane_05", {
        "plane" : plane(vector(2850, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Station 6: X = 3355 mm  (station_06_x3355mm.dxf)
    opPlane(context, id + "plane_06", {
        "plane" : plane(vector(3355, 0, 0) * millimeter,
                         vector(1, 0, 0)),
    });

    // Add a Loft manually across the sketch planes imported from DXF.
}, {});
