// -----------------------------------------------------------
// Auto-generated by onshape_uploader.py for: Moth Hull 4
// Paste into a Feature Studio, then add a Loft across the
// named sketch planes.
// -----------------------------------------------------------

FeatureScript 2176;
import(path : "onshape/std/geometry.fs", version : "2176.0");

annotation { "Feature Type Name" : "Hull Planes" }
export const hullPlanes = defineFeature(function(context is Context,
                                                  id is Id,
                                                  definition is map)
{
    const frontPlane = qBuiltinPart(BuiltInType.FRONT_PLANE);

    // Station 0: X = 0 mm  (station_00_x0000mm.dxf)
    opPlane(context, id + "plane_00", {
        "plane" : plane(vector(0, 0, 0) * millimeter,
                         Z_VEC),
    });

    // Station 1: X = 335 mm  (station_01_x0335mm.dxf)
    opPlane(context, id + "plane_01", {
        "plane" : plane(vector(0, 0, 335) * millimeter,
                         Z_VEC),
    });

    // Station 2: X = 939 mm  (station_02_x0939mm.dxf)
    opPlane(context, id + "plane_02", {
        "plane" : plane(vector(0, 0, 939) * millimeter,
                         Z_VEC),
    });

    // Station 3: X = 1677 mm  (station_03_x1677mm.dxf)
    opPlane(context, id + "plane_03", {
        "plane" : plane(vector(0, 0, 1677) * millimeter,
                         Z_VEC),
    });

    // Station 4: X = 2281 mm  (station_04_x2281mm.dxf)
    opPlane(context, id + "plane_04", {
        "plane" : plane(vector(0, 0, 2281) * millimeter,
                         Z_VEC),
    });

    // Station 5: X = 2851 mm  (station_05_x2851mm.dxf)
    opPlane(context, id + "plane_05", {
        "plane" : plane(vector(0, 0, 2851) * millimeter,
                         Z_VEC),
    });

    // Station 6: X = 3355 mm  (station_06_x3355mm.dxf)
    opPlane(context, id + "plane_06", {
        "plane" : plane(vector(0, 0, 3355) * millimeter,
                         Z_VEC),
    });

    // Add a Loft manually across the sketch planes imported from DXF.
}, {});
